# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
avalanchego_vms_list:
  timestampvm:
    id: tGas3T58KzdjLHhBDMnH2TvrddhqTji5iZAMZ3RXs2NLpSnhH
    aliases:
      - timestampvm
    download_url: https://github.com/Nuttymoon/timestampvm/releases/download
    binary_prefix: timestampvm-linux-amd64
    versions_comp:
      1.2.0:
        ge: 1.7.0
        le: 1.7.4
      1.2.1:
        ge: 1.7.4
        le: 1.7.4
      1.2.2:
        ge: 1.7.5
        le: 1.7.6
      1.2.3:
        ge: 1.7.7
        le: 1.7.7
    genesis_rpc_extra_path: ""
    genesis_build_method: timestampvm.encode
    genesis_json_key: bytes

  subnetevm:
    id: spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc
    aliases:
      - subnetevm
    download_url: https://github.com/Nuttymoon/subnet-evm/releases/download
    binary_prefix: subnetevm-linux-amd64
    versions_comp:
      0.1.0:
        ge: 1.7.0
        le: 1.7.4
      0.1.1:
        ge: 1.7.5
        le: 1.7.6
      0.1.2:
        ge: 1.7.5
        le: 1.7.6
      0.2.0:
        ge: 1.7.7
        le: 1.7.9
      0.2.1:
        ge: 1.7.10
        le: 1.7.10
    genesis_rpc_extra_path: "/rpc"
    genesis_build_method: subnetevm.buildGenesis
    genesis_json_key: genesisBytes

  spacesvm:
    id: sqja3uK17MJxfC7AN8nGadBw9JK5BcrsNwNynsqP5Gih8M5Bm
    aliases:
      - spacesvm
    download_url: https://github.com/Nuttymoon/spacesvm/releases/download
    binary_prefix: spacesvm-linux-amd64
    versions_comp:
      0.0.1:
        ge: 1.7.0
        le: 1.7.4
      0.0.2:
        ge: 1.7.5
        le: 1.7.6
      0.0.3:
        ge: 1.7.7
        le: 1.7.9
      0.0.4:
        ge: 1.7.10
        le: 1.7.10
