# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
# Avalanchego version
avalanchego_binary_name: "avalanchego-linux-amd64-v{{ avalanchego_version }}.tar.gz"
avalanchego_binary_url: "https://github.com/ava-labs/avalanchego/releases/download/v{{ avalanchego_version }}/{{ avalanchego_binary_name }}"

# Install directories
avalanchego_releases_dir: "{{ avalanchego_install_dir }}/releases"
avalanchego_current_dir: "{{ avalanchego_install_dir }}/current"
avalanchego_plugins_dir: "{{ avalanchego_current_dir }}/plugins"

# Configuration directories
avalanchego_subnets_conf_dir: "{{ avalanchego_conf_dir }}/subnets"
avalanchego_chains_conf_dir: "{{ avalanchego_conf_dir }}/chains"
avalanchego_vms_conf_dir: "{{ avalanchego_conf_dir }}/vms"

# Avalanche networks
avalanche_networks:
  fuji:
    c_chain:
      chain_id: 43113
      rpc_url: https://api.avax-test.network/ext/bc/C/rpc
      explorer_url: https://testnet.snowtrace.io
      explorer_api: https://api-testnet.snowtrace.io/api
      ash_router_addr: "0xB41b15Dc8C0Cd5A019e9F91ad5763Fb4aC571378"

# List of VMs supported by the collection
avalanchego_vms_list:
  blobvm:
    aliases:
      - blobvm
    binary_prefix: blobvm-linux-amd64
    download_url: https://github.com/AshAvalanche/blobvm/releases/download
    id: kM6h4LYe3AcEU1MB2UNg6ubzAiDAALZzpVrbX8zn3hXF6Avd8
    versions_comp:
      0.0.1:
        ge: 1.7.7
        le: 1.7.9
      0.0.2:
        ge: 1.7.7
        le: 1.7.9
      0.0.3:
        ge: 1.7.10
        le: 1.7.10
      0.0.4:
        ge: 1.7.11
        le: 1.7.12
      0.0.5:
        ge: 1.7.13
        le: 1.7.18
      0.0.6:
        ge: 1.7.13
        le: 1.7.18
      0.0.7:
        ge: 1.7.13
        le: 1.7.18
      0.0.8:
        ge: 1.8.0
        le: 1.8.6
      0.0.9:
        ge: 1.9.0
        le: 1.9.0
      0.0.10:
        ge: 1.9.1
        le: 1.9.2
      0.0.11:
        ge: 1.9.1
        le: 1.9.3
  spacesvm:
    aliases:
      - spacesvm
    binary_prefix: spacesvm-linux-amd64
    download_url: https://github.com/AshAvalanche/spacesvm/releases/download
    id: sqja3uK17MJxfC7AN8nGadBw9JK5BcrsNwNynsqP5Gih8M5Bm
    versions_comp:
      0.0.1:
        ge: 1.7.0
        le: 1.7.4
      0.0.2:
        ge: 1.7.5
        le: 1.7.6
      0.0.3:
        ge: 1.7.7
        le: 1.7.9
      0.0.4:
        ge: 1.7.10
        le: 1.7.10
      0.0.5:
        ge: 1.7.11
        le: 1.7.12
      0.0.6:
        ge: 1.7.13
        le: 1.7.18
      0.0.7:
        ge: 1.7.13
        le: 1.7.18
      0.0.8:
        ge: 1.8.0
        le: 1.8.6
      0.0.9:
        ge: 1.9.0
        le: 1.9.1
      0.0.10:
        ge: 1.9.2
        le: 1.9.2
      0.0.11:
        ge: 1.9.2
        le: 1.9.2
      0.0.12:
        ge: 1.9.3
        le: 1.9.3
      0.0.13:
        ge: 1.9.4
        le: 1.9.4
      0.0.14:
        ge: 1.9.4
        le: 1.9.4
      0.0.15:
        ge: 1.9.6
        le: 1.9.7
  subnetevm:
    aliases:
      - subnetevm
    binary_prefix: subnetevm-linux-amd64
    download_url: https://github.com/AshAvalanche/subnet-evm/releases/download
    genesis_build_method: subnetevm.buildGenesis
    genesis_json_key: genesisBytes
    genesis_rpc_extra_path: /rpc
    id: spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc
    versions_comp:
      0.1.0:
        ge: 1.7.0
        le: 1.7.4
      0.1.1:
        ge: 1.7.5
        le: 1.7.6
      0.1.2:
        ge: 1.7.5
        le: 1.7.6
      0.2.0:
        ge: 1.7.7
        le: 1.7.9
      0.2.1:
        ge: 1.7.10
        le: 1.7.10
      0.2.2:
        ge: 1.7.11
        le: 1.7.12
      0.2.3:
        ge: 1.7.13
        le: 1.7.16
      0.2.4:
        ge: 1.7.13
        le: 1.7.16
      0.2.5:
        ge: 1.7.13
        le: 1.7.16
      0.2.6:
        ge: 1.7.13
        le: 1.7.16
      0.2.7:
        ge: 1.7.13
        le: 1.7.16
      0.2.8:
        ge: 1.7.13
        le: 1.7.18
      0.2.9:
        ge: 1.7.13
        le: 1.7.18
      0.3.0:
        ge: 1.8.0
        le: 1.8.6
      0.4.0:
        ge: 1.9.0
        le: 1.9.0
      0.4.1:
        ge: 1.9.1
        le: 1.9.1
      0.4.2:
        ge: 1.9.1
        le: 1.9.1
      0.4.3:
        ge: 1.9.2
        le: 1.9.2
      0.4.4:
        ge: 1.9.2
        le: 1.9.3
      0.4.5:
        ge: 1.9.4
        le: 1.9.4
      0.4.6:
        ge: 1.9.4
        le: 1.9.4
      0.4.7:
        ge: 1.9.5
        le: 1.9.5
      0.4.8:
        ge: 1.9.6
        le: 1.9.8
      0.4.9:
        ge: 1.9.9
        le: 1.9.9
      0.4.10:
        ge: 1.9.9
        le: 1.9.9
  timestampvm:
    aliases:
      - timestampvm
    binary_prefix: timestampvm-linux-amd64
    download_url: https://github.com/AshAvalanche/timestampvm/releases/download
    genesis_build_method: timestampvm.encode
    genesis_json_key: bytes
    genesis_rpc_extra_path: ""
    id: tGas3T58KzdjLHhBDMnH2TvrddhqTji5iZAMZ3RXs2NLpSnhH
    versions_comp:
      1.2.0:
        ge: 1.7.0
        le: 1.7.4
      1.2.1:
        ge: 1.7.0
        le: 1.7.4
      1.2.2:
        ge: 1.7.5
        le: 1.7.6
      1.2.3:
        ge: 1.7.7
        le: 1.7.9
      1.2.4:
        ge: 1.7.10
        le: 1.7.10
      1.2.5:
        ge: 1.7.11
        le: 1.7.12
      1.2.6:
        ge: 1.7.13
        le: 1.7.18
      1.2.7:
        ge: 1.9.0
        le: 1.9.0
      1.2.8:
        ge: 1.9.1
        le: 1.9.1
      1.2.9:
        ge: 1.9.2
        le: 1.9.2
      1.3.0:
        ge: 1.9.3
        le: 1.9.3
