# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
# Avalanchego version
avalanchego_min_version: 1.9.6
avalanchego_binary_name: "avalanchego-linux-amd64-v{{ avalanchego_version }}.tar.gz"
avalanchego_binary_url: "https://github.com/ava-labs/avalanchego/releases/download/v{{ avalanchego_version }}/{{ avalanchego_binary_name }}"

# Install directories
avalanchego_releases_dir: "{{ avalanchego_install_dir }}/releases"
avalanchego_current_dir: "{{ avalanchego_install_dir }}/current"
avalanchego_plugins_dir: "{{ avalanchego_current_dir }}/plugins"

# Configuration directories
avalanchego_subnets_conf_dir: "{{ avalanchego_conf_dir }}/subnets"
avalanchego_chains_conf_dir: "{{ avalanchego_conf_dir }}/chains"
avalanchego_vms_conf_dir: "{{ avalanchego_conf_dir }}/vms"

# Avalanche networks
avalanche_networks:
  fuji:
    c_chain:
      chain_id: 43113
      rpc_url: https://api.avax-test.network/ext/bc/C/rpc
      explorer_url: https://testnet.snowtrace.io
      explorer_api: https://api-testnet.snowtrace.io/api
      ash_router_addr: "0xB41b15Dc8C0Cd5A019e9F91ad5763Fb4aC571378"

# String templates for VM files to download
avalanchego_vm_binary_filename: "{{ vm_name }}_{{ vm_version }}_linux_amd64.tar.gz"
avalanchego_vm_checksum_filename: "{{ vm_name }}_{{ vm_version }}_checksums.txt"

# List of VMs supported by the collection
avalanchego_vms_list:
  subnet-evm:
    aliases:
      - subnet-evm
    download_url: https://github.com/ava-labs/subnet-evm/releases/download
    genesis_build_method: subnetevm.buildGenesis
    genesis_json_key: genesisBytes
    genesis_rpc_extra_path: /rpc
    id: spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc
    versions_comp:
      0.4.8:
        ge: 1.9.6
        le: 1.9.8
      0.4.9:
        ge: 1.9.9
        le: 1.9.9
      0.4.10:
        ge: 1.9.9
        le: 1.9.9
      0.4.11:
        ge: 1.9.10
        le: 1.9.10
      0.4.12:
        ge: 1.9.10
        le: 1.9.10
