# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
# Network
avalanchego_http_host: 127.0.0.1
avalanchego_http_port: 9650

# Subnet
subnet_id: aUC7SX8QGVwsbwS4YNuavVTbinjJLrPjNNjdpZbbcFZZFSxFd
subnet_control_username: ewoq
subnet_control_password: I_l1ve_@_Endor

# Blockchain
blockchain_vm: subnet-evm
blockchain_name: Subnet EVM
blockchain_aliases:
  - subnet-evm
blockchain_genesis_params:
  genesisData:
    config:
      chainId: 13213
      homesteadBlock: 0
      eip150Block: 0
      eip150Hash: "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0"
      eip155Block: 0
      eip158Block: 0
      byzantiumBlock: 0
      constantinopleBlock: 0
      petersburgBlock: 0
      istanbulBlock: 0
      muirGlacierBlock: 0
      subnetEVMTimestamp: 0
      feeConfig:
        gasLimit: 8000000
        minBaseFee: 25000000000
        targetGas: 15000000
        baseFeeChangeDenominator: 36
        minBlockGasCost: 0
        maxBlockGasCost: 1000000
        targetBlockRate: 2
        blockGasCostStep: 200000
    alloc:
      8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC:
        balance: "0x295BE96E64066972000000"
    nonce: "0x0"
    timestamp: "0x0"
    extraData: "0x00"
    gasLimit: "0x7A1200"
    difficulty: "0x0"
    mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
    coinbase: "0x0000000000000000000000000000000000000000"
    number: "0x0"
    gasUsed: "0x0"
    parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
