# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- include_tasks: add-validator.yml
  vars:
    subnet_id: "{{ subnet_create_res.output.id }}"
  loop: "{{ subnet_validators_ids_list }}"
  loop_control:
    loop_var: node_id
  when: subnet_validators_add
