# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Check that Ash CLI is installed
  shell: ash help
  changed_when: false

- name: Create the Subnet
  include_tasks: create-subnet.yml

- name: Create the blockchains
  include_tasks: create-blockchain.yml
  vars:
    subnet_id: "{{ subnet_create_res.output.id }}"
  loop: "{{ subnet_blockchains_list }}"
  loop_control:
    loop_var: blockchain
    label: "{{ blockchain.name }}"

- name: Add nodes as Subnet validators from node IDs
  include_tasks: add-validator.yml
  vars:
    subnet_id: "{{ subnet_create_res.output.id }}"
  loop: "{{ subnet_validators_ids_list }}"
  loop_control:
    loop_var: node_id
  when: subnet_validators_add

- name: Get Subnet information
  ash.avalanche.ash_cmd:
    command: "avalanche subnet info {{ subnet_create_res.output.id }}"
  environment:
    AVALANCHE_NETWORK: "{{ subnet_avalanche_network_id }}"
  register: subnet_info_res
