# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Check that Ash CLI is installed
  shell: ash help
  changed_when: false
  tags:
    - create
    - create-subnet
    - create-blockchains

- name: Create the Subnet
  import_tasks: create-subnet.yml
  tags:
    - create
    - create-subnet

- name: Create the blockchains
  import_tasks: create-blockchains.yml
  tags:
    - create
    - create-blockchains

- name: Add nodes as Subnet validators from node IDs
  import_tasks: add-validators.yml
  tags:
    - validate
    - add-validators

- name: Get Subnet information
  ash.avalanche.ash_cmd:
    command: "avalanche subnet info {{ subnet_create_res.output.id }}"
  environment:
    AVALANCHE_NETWORK: "{{ subnet_avalanche_network_id }}"
  register: subnet_info_res
  tags:
    - create
    - create-subnet
    - create-blockchains
    - validate
    - add-validators
