# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Initialize the default Ash CLI configuration
  command:
    cmd: ash conf init --config {{ ash_cli_conf_dir }}/default.yml
    creates: "{{ ash_cli_conf_dir }}/default.yml"

- name: Add local network configuration
  blockinfile:
    path: "{{ ash_cli_conf_dir }}/default.yml"
    block: |
      - name: local
        subnets:
        - id: 11111111111111111111111111111111LpoYY
          controlKeys: []
          threshold: 0
          blockchains:
          - id: 11111111111111111111111111111111LpoYY
            name: P-Chain
            vmId: 11111111111111111111111111111111LpoYY
            vmType: PVM
            rpcUrl: {{ avalanche_pchain_local_url }}
    insertafter: "avalancheNetworks:"
  when: avalanche_network_id == "local"
