# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Install AvalancheGo
  include_tasks: install-avalanchego.yml

- name: Clean plugins dir
  include_tasks: clean-plugins-dir.yml

- name: Install VMs
  include_tasks: install-vm.yml
  vars:
    vm_name: "{{ vm.split('=')[0] }}"
    vm_version: "{{ vm.split('=')[1] }}"
    vm_info: "{{ avalanchego_vms_list[vm.split('=')[0]] }}"
  loop: "{{ avalanchego_vms_install }}"
  loop_control:
    loop_var: vm

- name: Configure AvalancheGo node
  include_tasks: config-node.yml

- name: Configure subnets
  include_tasks: config-subnets.yml

- name: Configure chains
  include_tasks: config-chains.yml

- name: Start AvalancheGo node
  include_tasks: start.yml

- name: Generate Ash CLI local network configuration
  set_fact:
    ash_cli_custom_networks:
      local:
        info_rpc_url: "{{ ash_cli_local_endpoint }}/ext/info"
        pchain_rpc_url: "{{ ash_cli_local_endpoint }}/ext/bc/P"
        cchain_rpc_url: "{{ ash_cli_local_endpoint }}/ext/bc/C/rpc"
        xchain_rpc_url: "{{ ash_cli_local_endpoint }}/ext/bc/X"
  vars:
    ash_cli_local_endpoint: "{{ 'https' if avalanchego_https_enabled else 'http' }}://{{ '127.0.0.1' if avalanchego_http_host == '0.0.0.0' else avalanchego_http_host }}:{{ avalanchego_http_port }}"
  when: avalanchego_network_id == 'local'

- name: Install and configure Ash CLI
  include_role:
    name: ash.avalanche.ash_cli
  vars:
    ash_cli_avalanche_network_id: "{{ avalanchego_network_id }}"
  when: ash_cli_install
