# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Install AvalancheGo
  import_tasks: install-avalanchego.yml
  tags:
    - install
    - avalanchego

- name: Clean plugins dir
  import_tasks: clean-plugins-dir.yml
  tags:
    - install
    - vms

- name: Install VMs
  import_tasks: install-vms.yml
  tags:
    - install
    - vms

- name: Configure AvalancheGo node
  import_tasks: config-node.yml
  tags:
    - config
    - avalanchego

- name: Configure subnets
  import_tasks: config-subnets.yml
  tags:
    - config
    - subnets

- name: Configure chains
  import_tasks: config-chains.yml
  tags:
    - config
    - chains

- name: Start AvalancheGo node
  import_tasks: start.yml
  tags:
    - start
    - avalanchego

- name: Generate Ash CLI local network configuration
  set_fact:
    ash_cli_custom_networks:
      local:
        pchain_rpc_url: "{{ ash_cli_local_endpoint }}/ext/bc/P"
        cchain_rpc_url: "{{ ash_cli_local_endpoint }}/ext/bc/C/rpc"
        xchain_rpc_url: "{{ ash_cli_local_endpoint }}/ext/bc/X"
  tags:
    - install
    - ash_cli
  vars:
    ash_cli_local_endpoint: "{{ 'https' if avalanchego_https_enabled else 'http' }}://{{ '127.0.0.1' if avalanchego_http_host == '0.0.0.0' else avalanchego_http_host }}:{{ avalanchego_http_port }}"
  when: avalanchego_network_id == 'local'

- name: Install and configure Ash CLI
  import_role:
    name: ash.avalanche.ash_cli
  tags:
    - install
    - ash_cli
  vars:
    ash_cli_avalanche_network_id: "{{ avalanchego_network_id }}"
  when: ash_cli_install
