# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Restart AvalancheGo and reload VMs if needed
  meta: flush_handlers

- name: Start and enable avalanchego.service
  service:
    name: avalanchego
    state: started
    enabled: true
