# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Add validator playbook
  hosts: avalanche_nodes
  tasks:
    - name: Add validator task
      include_role:
        name: ash.avalanche.node
        tasks_from: add-validator.yml
