# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Create admin user playbook
  hosts: avalanche_nodes
  tasks:
    - name: Create admin user task
      include_role:
        name: ash.avalanche.node
        tasks_from: admin-user.yml
